### ISSUE TITLE
Great Plugin !! Can you see if this is possible ?

### ISSUE THREAD

**Issue by toneegee** [asleepwalker/jquery-ui.accordion.multiple#1]
Hi, great job in this nice plugin !
How would you customize the accordion icons, please ?

Many many thanks in advance!

**Comment by asleepwalker** [comment]
Are you talking about this?
http://jqueryui.com/accordion/#custom-icons

**Comment by toneegee** [comment]
Hi, yes !

I have recreated this here:
https://jsfiddle.net/firegroove/93z2a1sh/
And changed the icons to PLUS sign...easy

Now, for your plugin, it's a bit different....I can't find the class or
parameters to change icons to custom ones ! :))

Best regards



2017-09-07 22:40 GMT+02:00 Artyom Fedosov <notifications@github.com>:

**Comment by asleepwalker** [comment]
Okay, I'll take a look. Thanks for reporting.

**Comment by toneegee** [comment]
Hello,

Actually, I figured it out, I just added this :

$('#accordion').accordion({
collapsible: true,
multiple: false,
heightStyle: "content",
icons: {
activeHeader: "ui-icon-arrowthick-1-s",
header: "ui-icon-arrowthick-1-e"
},
});

I am new to JS :) In this case I configured the custom icons to
arrowthick,and need to change two lines in CSS.
If you want to have a look here :
https://jsfiddle.net/firegroove/3j73r6x6/

<https://jsfiddle.net/firegroove/3j73r6x6/>
Let me know what you think, that would be so great :)


Best regards,

Tonee


2017-09-08 13:56 GMT+02:00 Artyom Fedosov <notifications@github.com>:
